import { Inter } from 'next/font/google'
import SideMenu from '../(components)/sidemenu'
import React from 'react'
import '../globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}) {
    return (
        <div className="w-full h-full flex">

            <div className="w-2/12 h-full bg-pure">
                <SideMenu />
            </div>

            <div className="w-full h-screen flex flex-col items-center justify-center align-middle bg-gray-100">
                {children}
            </div>
        </div>

    )
}
